/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package okhttp_h2;

import java.io.IOException;

public class Main {

    public static void main(String[] args)
        throws IOException, Exception
    {
        String homeDir = System.getenv("HOME");
        H2Client client = new H2Client();

        // client.requestGet("https://o49.iasdf.com/ip");

        // client.uploadFile("http://o49.iasdf.com/uploads",
        //     homeDir + "/db/growcastle/background.sh");

        // client.uploadFile("http://o49.iasdf.com/uploads",
        //     homeDir + "/db/growcastle/h2-2.2.224.jar");

        // client.uploadFile("https://49.iasdf.com/uploads",
        //     homeDir + "/db/growcastle/h2-2.2.224.jar");

        client.uploadFile("https://49.iasdf.com/uploads",
            homeDir + "/db/h2-2023-09-17.zip");

    }
}


